--<ScriptOptions statementTerminator=";"/>
   CREATE SEQUENCE  "TOLEDO"."PRINCIPALSEQ"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;
   CREATE SEQUENCE  "TOLEDO"."PRIVILEGESEQ"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;
   CREATE SEQUENCE  "TOLEDO"."ROLESEQ"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;
   CREATE SEQUENCE  "TOLEDO"."SERVICESEQ"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;
   CREATE SEQUENCE  "TOLEDO"."STORESEQ"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;


ALTER TABLE "TOLEDO"."PRINCIPAL" DROP CONSTRAINT "PRINCIPAL_PK";

DROP TABLE "TOLEDO"."PRINCIPAL";

CREATE TABLE "TOLEDO"."PRINCIPAL" 
   (	"PRINCIPAL_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"LOCKED" VARCHAR2(255 BYTE), 
	"NAME" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "PRINCIPAL_PK" PRIMARY KEY ("PRINCIPAL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  ALTER TABLE "TOLEDO"."ROLE" DROP CONSTRAINT "ROLE_PK";
  DROP TABLE "TOLEDO"."ROLE";
  CREATE TABLE "TOLEDO"."ROLE" 
   (	"ROLE_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "ROLE_PK" PRIMARY KEY ("ROLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
  ALTER TABLE "TOLEDO"."PRINCIPAL_ROLES" DROP CONSTRAINT "PRINCIPAL_ROLES_PK";
  ALTER TABLE "TOLEDO"."PRINCIPAL_ROLES" DROP CONSTRAINT "PRINCIPAL_ROLES_PRINCIPAL_FK";
  ALTER TABLE "TOLEDO"."PRINCIPAL_ROLES" DROP CONSTRAINT "PRINCIPAL_ROLES_ROLE_FK";
  DROP TABLE "TOLEDO"."PRINCIPAL_ROLES";
    CREATE TABLE "TOLEDO"."PRINCIPAL_ROLES" 
   (	"PRINCIPAL_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"ROLE_ID" NUMBER(19,0) NOT NULL ENABLE, 
	 CONSTRAINT "PRINCIPAL_ROLES_PK" PRIMARY KEY ("PRINCIPAL_ID", "ROLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "PRINCIPAL_ROLES_PRINCIPAL_FK" FOREIGN KEY ("PRINCIPAL_ID")
	  REFERENCES "TOLEDO"."PRINCIPAL" ("PRINCIPAL_ID") ENABLE, 
	 CONSTRAINT "PRINCIPAL_ROLES_ROLE_FK" FOREIGN KEY ("ROLE_ID")
	  REFERENCES "TOLEDO"."ROLE" ("ROLE_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

    ALTER TABLE "TOLEDO"."PRIVILEGE" DROP CONSTRAINT "PRIVILEGE_PK";
      DROP TABLE "TOLEDO"."PRIVILEGE";
    CREATE TABLE "TOLEDO"."PRIVILEGE" 
   (	"PRIV_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	 CONSTRAINT "PRIVILEGE_PK" PRIMARY KEY ("PRIV_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
  ALTER TABLE "TOLEDO"."ROLE_PRIVILEGES" DROP CONSTRAINT "ROLE_PRIVILEGES_PK";
  ALTER TABLE "TOLEDO"."ROLE_PRIVILEGES" DROP CONSTRAINT "ROLE_PRIVILEGES_PRIVILEGE_FK";
  ALTER TABLE "TOLEDO"."ROLE_PRIVILEGES" DROP CONSTRAINT "ROLE_PRIVILEGES_ROLE_FK";
  DROP TABLE "TOLEDO"."ROLE_PRIVILEGES";
   CREATE TABLE "TOLEDO"."ROLE_PRIVILEGES" 
   (	"ROLE_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"PRIV_ID" NUMBER(19,0) NOT NULL ENABLE, 
	 CONSTRAINT "ROLE_PRIVILEGES_PK" PRIMARY KEY ("ROLE_ID", "PRIV_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "ROLE_PRIVILEGES_PRIVILEGE_FK" FOREIGN KEY ("PRIV_ID")
	  REFERENCES "TOLEDO"."PRIVILEGE" ("PRIV_ID") ENABLE, 
	 CONSTRAINT "ROLE_PRIVILEGES_ROLE_FK" FOREIGN KEY ("ROLE_ID")
	  REFERENCES "TOLEDO"."ROLE" ("ROLE_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
   ALTER TABLE "TOLEDO"."STORE" DROP CONSTRAINT "STORE_PK";
  DROP TABLE "TOLEDO"."STORE";
  CREATE TABLE "TOLEDO"."STORE" 
   (	"STORE_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"ADDRESS" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"CITY" VARCHAR2(255 BYTE), 
	"COUNTRY" VARCHAR2(255 BYTE), 
	"LATITUDE" NUMBER(19,2) NOT NULL ENABLE, 
	"LOGITITUDE" NUMBER(19,2) NOT NULL ENABLE, 
	"NAME" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"PHONE" VARCHAR2(255 BYTE), 
	"STATE" VARCHAR2(255 BYTE), 
	 CONSTRAINT "STORE_PK" PRIMARY KEY ("STORE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
   ALTER TABLE "TOLEDO"."SERVICE" DROP CONSTRAINT "SERVICE_PK";
  DROP TABLE "TOLEDO"."SERVICE";
   CREATE TABLE "TOLEDO"."SERVICE" 
   (	"SERVICE_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	 CONSTRAINT "SERVICE_PK" PRIMARY KEY ("SERVICE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
   ALTER TABLE "TOLEDO"."STORE_SERVICES" DROP CONSTRAINT "STORE_SERVICES_PK";
  ALTER TABLE "TOLEDO"."STORE_SERVICES" DROP CONSTRAINT "STORE_SERVICES_SERVICE_FK";
  ALTER TABLE "TOLEDO"."STORE_SERVICES" DROP CONSTRAINT "STORE_SERVICES_STORE_FK";
  DROP TABLE "TOLEDO"."STORE_SERVICES";
    CREATE TABLE "TOLEDO"."STORE_SERVICES" 
   (	"STORE_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"SERVICE_ID" NUMBER(19,0) NOT NULL ENABLE, 
	 CONSTRAINT "STORE_SERVICES_PK" PRIMARY KEY ("STORE_ID", "SERVICE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "STORE_SERVICES_SERVICE_FK" FOREIGN KEY ("SERVICE_ID")
	  REFERENCES "TOLEDO"."SERVICE" ("SERVICE_ID") ENABLE, 
	 CONSTRAINT "STORE_SERVICES_STORE_FK" FOREIGN KEY ("STORE_ID")
	  REFERENCES "TOLEDO"."STORE" ("STORE_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;